name: pandas_talk
channels:
  - defaults
  - conda-forge
  - rapidsai
dependencies:
  - jupyter
  - rise
  - numpy=1.16.2
  - pandas=0.24.2
  - matplotlib=3.1.0
  - seaborn=0.9.0
  - pip=19.1.1
  - pip:
    - plotly==3.10.0
    - cufflinks==0.8.2
